Switch user_started_course to is_user_enrolled
woocommerce/sensei-content-drip pull request #193
Opened 2020-03-20 09:58 UTC by gkaragia

#### Changes proposed in this Pull Request:

This change switches usages of `Sensei_Utils::user_started_course` to `Sensei_Course::is_user_enrolled. The calls to `Sensei_Utils::user_started_course` can't be removed completely since we must support pre v3 core Sensei.

#### Testing instructions:

* Create a course and link it to a product. Add two lessons to it which drip in the future. One lesson should drip to a static date and one on a date which is based on user's start date.
* Check that a user that bought the product can't access the lessons.
* Disable 'Access Permissions' setting.
* Check that the user still can't access lessons.
* Logout and check that the lessons still can't be accessed.
* Remove the content drip dates from lessons and check that the lessons can be accessed.

2020-03-20 14:29 UTC, jom requested changes
Few minor things, otherwise looks good. Took me a while to trace the logic that these methods were using... it is a strange case (not enrolled AND lesson blocked).

2020-03-20 14:29 UTC, jom commented on includes/class-scd-ext-access-control.php
> +			$user_started_course = Sensei_Utils::user_started_course( $lesson_course_id, get_current_user_id() );
I wonder if it would make more sense to change the vars and comments (below) to match enrolment.

2020-03-23 13:43 UTC, gkaragia commented
> Took me a while to trace the logic that these methods were using... it is a strange case (not enrolled AND lesson blocked).

Yeah the logic is a bit confusing here unfortunately. I tried to have a look into refactoring it but I decided that it's hard enough to do it in its own PR.

2020-03-24 08:18 UTC, jom approved these changes
Looks good!

2020-03-24 08:58 UTC, merged